services:
  cdm-rabbitmq:
    image: rabbitmq:3-management
    container_name: CDM_RABBIT_MQ
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env.docker.rabbitmq
    networks:
      - cdm-network
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

  cdm-wallet-db:
    image: postgres:15
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - cdm-wallet-db:/var/lib/postgresql/data
    networks:
      - cdm-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres_wallet" ]
      interval: 10s
      timeout: 5s
      retries: 5

  cdm-wallet-service:
    build: .
    env_file:
      - .env.docker
    ports:
      - "4006:4006"
    depends_on:
      cdm-wallet-db:
        condition: service_healthy
      cdm-rabbitmq:
        condition: service_healthy
    networks:
      - cdm-network

volumes:
  cdm-wallet-db:

networks:
  cdm-network:
    driver: bridge
